In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler

In [2]:
df = pd.read_csv("data/Indian ODI Cricketers.csv")

In [3]:
df.head()

,No,Name,First,Last,Mat,Inn,NO.1,Runs,HS,Avg,Balls,Mdn,Runs_1,Wkt,BBM,Avg_2,Ca,St
0,1,Syed Abid Ali,1974,1975,5,3,0,93,70,31.00,336,10,187,7,2/22,26.71,0,0
1,2,Bishan Singh Bedi,1974,1979,10,7,2,31,13,6.20,590,17,340,7,2/44,48.57,4,0
2,3,Farokh Engineer,1974,1975,5,4,1,114,54*,38.00,—,—,—,—,—,—,3,1
3,4,Sunil Gavaskar,1974,1987,108,102,14,3092,103*,35.13,20,0,25,1,1/10,25.00,22,0
4,5,Madan Lal,1974,1987,67,35,14,401,53*,19.09,3164,44,2137,73,4/20,29.27,18,0

In [4]:
df.columns

Index(['No', 'Name', 'First', 'Last', 'Mat', 'Inn', 'NO.1', 'Runs', 'HS',
       'Avg', 'Balls', 'Mdn', 'Runs_1', 'Wkt', 'BBM', 'Avg_2', 'Ca', 'St'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   No      250 non-null    int64
 1   Name    250 non-null    str
 2   First   250 non-null    int64
 3   Last    250 non-null    int64
 4   Mat     250 non-null    int64
 5   Inn     250 non-null    str
 6   NO.1    250 non-null    str
 7   Runs    250 non-null    str
 8   HS      250 non-null    str
 9   Avg     249 non-null    str
 10  Balls   250 non-null    str
 11  Mdn     250 non-null    str
 12  Runs_1  250 non-null    str
 13  Wkt     250 non-null    str
 14  BBM     250 non-null    str
 15  Avg_2   250 non-null    str
 16  Ca      250 non-null    int64
 17  St      250 non-null    int64
dtypes: int64(6), str(12)
memory usage: 35.3 KB

In [6]:
df.replace('—', np.nan, inplace=True)

numeric_cols = [
    'Inn',
    'NO.1',
    'Runs',
    'Avg',
    'Balls',
    'Mdn',
    'Runs_1',
    'Wkt',
    'Avg_2'
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.fillna(0, inplace=True)

TypeError: Invalid value '0' for dtype 'str'. Value should be a string or missing value, got 'int' instead.

In [8]:
import pandas as pd
import numpy as np

# Replace special dash values
df.replace('—', np.nan, inplace=True)

# Numeric columns
numeric_cols = [
    'Inn',
    'NO.1',
    'Runs',
    'Avg',
    'Balls',
    'Mdn',
    'Runs_1',
    'Wkt',
    'Avg_2'
]

# Convert to numeric
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Fill NaN ONLY in numeric columns
df[numeric_cols] = df[numeric_cols].fillna(0)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   No      250 non-null    int64
 1   Name    250 non-null    str
 2   First   250 non-null    int64
 3   Last    250 non-null    int64
 4   Mat     250 non-null    int64
 5   Inn     250 non-null    float64
 6   NO.1    250 non-null    float64
 7   Runs    250 non-null    float64
 8   HS      241 non-null    str
 9   Avg     250 non-null    float64
 10  Balls   250 non-null    float64
 11  Mdn     250 non-null    float64
 12  Runs_1  250 non-null    float64
 13  Wkt     250 non-null    float64
 14  BBM     165 non-null    str
 15  Avg_2   250 non-null    float64
 16  Ca      250 non-null    int64
 17  St      250 non-null    int64
dtypes: float64(9), int64(6), str(3)
memory usage: 35.3 KB

In [10]:
# Avoid division by zero
df['Balls'] = df['Balls'].replace(0, 1)
df['Inn'] = df['Inn'].replace(0, 1)

# Batting strike rate
df['strike_rate'] = (df['Runs'] / df['Balls']) * 100

# Cons

In [11]:
# Avoid divide by zero
df['Balls'] = df['Balls'].replace(0, 1)

# Strike rate
df['strike_rate'] = (df['Runs'] / df['Balls']) * 100

# Consistency
df['Inn'] = df['Inn'].replace(0, 1)

df['consistency'] = df['Runs'] / df['Inn']

In [12]:
df['batsman_score'] = (
    df['Avg'] * 0.40 +
    df['strike_rate'] * 0.30 +
    df['Runs'] * 0.20 +
    df['consistency'] * 0.10
)

In [13]:
df['bowler_score'] = (
    df['Wkt'] * 0.50 +
    (1 / (df['Avg_2'] + 1)) * 100 * 0.30 +
    df['Mdn'] * 0.20
)

In [14]:
recent_df = df[df['Last'] >= 2020]

In [16]:
recent_df

,No,Name,First,Last,Mat,Inn,NO.1,Runs,HS,Avg,...,Runs_1,Wkt,BBM,Avg_2,Ca,St,strike_rate,consistency,batsman_score,bowler_score
167,168,Rohit Sharma,2007,2023,243,236.0,34.0,9825.0,264,48.63,...,515.0,8.0,2/27,64.37,87,0,1656.829680,41.631356,2485.664039,4.858926
174,175,Virat Kohli,2008,2023,274,265.0,40.0,12898.0,183,57.32,...,665.0,4.0,1/15,166.25,141,0,2012.168487,48.671698,3211.045716,2.379372
176,177,Ravindra Jadeja,2009,2023,174,118.0,41.0,2526.0,87,32.80,...,7142.0,191.0,5/36,37.39,65,0,28.951289,21.406780,529.146065,106.281454
184,185,Ravichandran Ashwin,2010,2022,113,63.0,20.0,707.0,65,16.07,...,5058.0,151.0,4/25,33.49,30,0,11.512783,11.222222,152.404057,83.569817
187,188,Shikhar Dhawan,2010,2022,167,164.0,10.0,6793.0,143,44.11,...,0.0,0.0,NaN,0.00,83,0,679300.000000,41.420732,205170.386073,30.000000
193,194,Bhuvneshwar Kumar,2012,2022,121,55.0,16.0,552.0,53*,14.15,...,4951.0,141.0,5/42,35.11,29,0,9.440739,10.036364,119.895858,84.930795
194,195,Mohammed Shami,2013,2023,90,43.0,19.0,204.0,25,8.50,...,4210.0,162.0,5/69,25.98,29,0,4.527297,4.744186,46.032608,91.111935
201,202,Axar Patel,2014,2023,51,31.0,10.0,412.0,64*,19.61,...,1822.0,58.0,3/24,31.41,23,0,17.060041,13.290323,96.691045,33.525640
204,205,Kedar Jadhav,2014,2020,73,52.0,19.0,1389.0,120,42.09,...,1020.0,27.0,3/23,37.77,33,0,117.017692,26.711538,332.412461,14.473794
205,206,Manish Pandey,2015,2021,29,24.0,7.0,566.0,104*,33.29,...,0.0,0.0,NaN,0.00,10,0,56600.000000,23.583333,17108.874333,30.000000
209,210,Jasprit Bumrah,2016,2022,72,20.0,13.0,47.0,14*,6.71,...,2941.0,121.0,6/19,24.30,17,0,1.234568,2.350000,12.689370,70.285771
210,211,Yuzvendra Chahal,2016,2023,72,14.0,5.0,77.0,18*,8.55,...,3283.0,121.0,6/42,27.13,16,0,2.059374,5.500000,19.987812,64.366477
212,213,KL Rahul,2016,2023,54,52.0,8.0,1986.0,112,45.13,...,0.0,0.0,NaN,0.00,32,2,198600.000000,38.192308,59999.071231,30.000000
214,215,Hardik Pandya,2016,2023,74,55.0,7.0,1584.0,92*,33.00,...,2711.0,72.0,4/24,37.65,30,0,54.696133,28.800000,349.288840,38.976197
215,216,Jayant Yadav,2016,2022,2,2.0,1.0,3.0,2,3.00,...,61.0,1.0,1/8,61.00,1,0,3.571429,1.500000,3.021429,0.983871
216,217,Kuldeep Yadav,2017,2023,81,30.0,16.0,156.0,19,11.14,...,3683.0,134.0,6/25,27.48,12,0,3.684459,5.200000,37.281338,72.053371
217,218,Shardul Thakur,2017,2023,35,21.0,6.0,298.0,50*,19.86,...,1599.0,50.0,4/52,31.98,7,0,19.338092,14.190476,74.764475,27.709642
218,219,Shreyas Iyer,2017,2023,42,38.0,3.0,1631.0,113*,46.60,...,39.0,0.0,NaN,0.00,16,0,4408.108108,42.921053,1671.564538,30.000000
219,220,Washington Sundar,2017,2023,16,9.0,1.0,233.0,51,29.12,...,435.0,16.0,3/30,27.18,4,0,45.155039,25.888889,74.383401,9.464585
222,223,Deepak Chahar,2018,2022,13,9.0,3.0,203.0,69*,33.83,...,489.0,16.0,3/27,30.56,1,0,39.803922,22.555556,68.328732,9.950570
223,224,Rishabh Pant,2018,2022,30,26.0,1.0,865.0,125*,34.60,...,0.0,0.0,NaN,0.00,26,1,86500.000000,33.269231,26140.166923,30.000000
224,225,Mohammed Siraj,2019,2023,24,10.0,5.0,30.0,9,6.00,...,891.0,43.0,4/32,20.72,5,0,2.683363,3.000000,9.505009,26.681215
226,227,Shubman Gill,2019,2023,24,24.0,4.0,1311.0,208,65.55,...,0.0,0.0,NaN,0.00,15,0,131100.000000,54.625000,39623.882500,30.000000
228,229,Navdeep Saini,2019,2021,8,5.0,3.0,107.0,45,53.50,...,481.0,6.0,2/58,80.16,3,0,25.476190,21.400000,52.582857,3.369640
229,230,Mayank Agarwal,2020,2020,5,5.0,0.0,86.0,32,17.20,...,0.0,0.0,NaN,0.00,2,0,8600.000000,17.200000,2605.800000,30.000000
230,231,Prithvi Shaw,2020,2021,6,6.0,0.0,189.0,49,31.50,...,0.0,0.0,NaN,0.00,2,0,18900.000000,31.500000,5723.550000,30.000000
231,232,T. Natarajan,2020,2021,2,1.0,0.0,0.0,0*,0.00,...,143.0,3.0,2/70,47.66,0,0,0.000000,0.000000,0.000000,2.316523
232,233,Krunal Pandya,2021,2021,5,4.0,2.0,130.0,58*,65.00,...,223.0,2.0,1/26,111.50,1,0,57.017544,32.500000,72.355263,1.466667
233,234,Prasidh Krishna,2021,2022,14,5.0,3.0,2.0,2*,1.00,...,598.0,25.0,4/12,23.92,2,0,0.296736,0.400000,0.929021,15.103852
234,235,Ishan Kishan,2021,2023,14,13.0,1.0,510.0,210,42.50,...,0.0,0.0,NaN,0.00,5,2,51000.000000,39.230769,15422.923077,30.000000
235,236,Suryakumar Yadav,2021,2023,23,21.0,3.0,433.0,64,24.05,...,0.0,0.0,NaN,0.00,14,0,43300.000000,20.619048,13088.281905,30.000000
236,237,Rahul Chahar,2021,2021,1,1.0,0.0,13.0,13,13.00,...,54.0,3.0,3/54,18.00,0,0,21.666667,13.000000,15.600000,3.078947
237,238,Krishnappa Gowtham,2021,2021,1,1.0,0.0,2.0,2,2.00,...,49.0,1.0,1/49,49.00,1,0,4.166667,2.000000,2.650000,1.100000
238,239,Nitish Rana,2021,2021,1,1.0,0.0,7.0,7,7.00,...,10.0,0.0,NaN,0.00,0,0,38.888889,7.000000,16.566667,30.000000
239,240,Chetan Sakariya,2021,2021,1,1.0,0.0,0.0,0*,0.00,...,34.0,2.0,2/34,17.00,2,0,0.000000,0.000000,0.000000,2.666667
240,241,Sanju Samson,2021,2022,11,10.0,5.0,330.0,86*,66.00,...,0.0,0.0,NaN,0.00,7,2,33000.000000,33.000000,9995.700000,30.000000
241,242,Venkatesh Iyer,2022,2022,2,2.0,0.0,24.0,22,12.00,...,28.0,0.0,NaN,0.00,0,0,80.000000,12.000000,34.800000,30.000000
242,243,Deepak Hooda,2022,2022,10,7.0,1.0,153.0,33,25.50,...,119.0,3.0,1/6,39.66,3,0,102.000000,21.857143,73.585714,2.437826
243,244,Avesh Khan,2022,2022,5,2.0,0.0,13.0,10,6.50,...,214.0,3.0,3/66,71.33,3,0,6.103286,6.500000,7.680986,2.314766
244,245,Ruturaj Gaikwad,2022,2022,1,1.0,0.0,19.0,19,19.00,...,0.0,0.0,NaN,0.00,0,0,1900.000000,19.000000,583.300000,30.000000
245,246,Ravi Bishnoi,2022,2022,1,1.0,1.0,4.0,4*,0.00,...,69.0,1.0,1/69,69.00,0,0,8.333333,4.000000,3.700000,0.928571
246,247,Shahbaz Ahmed,2022,2022,3,1.0,0.0,0.0,0,0.00,...,125.0,3.0,2/32,41.66,1,0,0.000000,0.000000,0.000000,2.203235
247,248,Arshdeep Singh,2022,2022,3,1.0,0.0,9.0,9,9.00,...,89.0,0.0,NaN,0.00,0,0,11.392405,9.000000,9.717722,30.200000
248,249,Umran Malik,2022,2023,8,3.0,3.0,2.0,2*,0.00,...,355.0,13.0,3/57,27.30,1,0,0.606061,0.666667,0.648485,7.960071
249,250,Kuldeep Sen,2022,2022,1,1.0,1.0,2.0,2*,0.00,...,37.0,2.0,2/37,18.50,0,0,6.666667,2.000000,2.600000,2.538462

In [19]:
recent_df['Balls'] = recent_df['Balls'].replace(0, 1)

recent_df['strike_rate'] = (
    recent_df['Runs'] / recent_df['Balls']
) * 100

In [20]:
recent_df['batsman_score'] = (
    recent_df['Avg'] * 0.40 +
    recent_df['strike_rate'] * 0.30 +
    recent_df['Runs'] * 0.20 +
    recent_df['consistency'] * 0.10
)

In [21]:
top_batsmen = recent_df.sort_values(
    by='batsman_score',
    ascending=False
)

print(top_batsmen[['Name', 'Last', 'batsman_score']].head(11))

                 Name  Last  batsman_score
187   Shikhar Dhawan   2022  205170.386073
212        KL Rahul    2023   59999.071231
226      Shubman Gill  2023   39623.882500
223     Rishabh Pant   2022   26140.166923
205     Manish Pandey  2021   17108.874333
234      Ishan Kishan  2023   15422.923077
235  Suryakumar Yadav  2023   13088.281905
240      Sanju Samson  2022    9995.700000
230      Prithvi Shaw  2021    5723.550000
174      Virat Kohli   2023    3211.045716
229    Mayank Agarwal  2020    2605.800000

In [22]:
recent_df

,No,Name,First,Last,Mat,Inn,NO.1,Runs,HS,Avg,...,Runs_1,Wkt,BBM,Avg_2,Ca,St,strike_rate,consistency,batsman_score,bowler_score
167,168,Rohit Sharma,2007,2023,243,236.0,34.0,9825.0,264,48.63,...,515.0,8.0,2/27,64.37,87,0,1656.829680,41.631356,2485.664039,4.858926
174,175,Virat Kohli,2008,2023,274,265.0,40.0,12898.0,183,57.32,...,665.0,4.0,1/15,166.25,141,0,2012.168487,48.671698,3211.045716,2.379372
176,177,Ravindra Jadeja,2009,2023,174,118.0,41.0,2526.0,87,32.80,...,7142.0,191.0,5/36,37.39,65,0,28.951289,21.406780,529.146065,106.281454
184,185,Ravichandran Ashwin,2010,2022,113,63.0,20.0,707.0,65,16.07,...,5058.0,151.0,4/25,33.49,30,0,11.512783,11.222222,152.404057,83.569817
187,188,Shikhar Dhawan,2010,2022,167,164.0,10.0,6793.0,143,44.11,...,0.0,0.0,NaN,0.00,83,0,679300.000000,41.420732,205170.386073,30.000000
193,194,Bhuvneshwar Kumar,2012,2022,121,55.0,16.0,552.0,53*,14.15,...,4951.0,141.0,5/42,35.11,29,0,9.440739,10.036364,119.895858,84.930795
194,195,Mohammed Shami,2013,2023,90,43.0,19.0,204.0,25,8.50,...,4210.0,162.0,5/69,25.98,29,0,4.527297,4.744186,46.032608,91.111935
201,202,Axar Patel,2014,2023,51,31.0,10.0,412.0,64*,19.61,...,1822.0,58.0,3/24,31.41,23,0,17.060041,13.290323,96.691045,33.525640
204,205,Kedar Jadhav,2014,2020,73,52.0,19.0,1389.0,120,42.09,...,1020.0,27.0,3/23,37.77,33,0,117.017692,26.711538,332.412461,14.473794
205,206,Manish Pandey,2015,2021,29,24.0,7.0,566.0,104*,33.29,...,0.0,0.0,NaN,0.00,10,0,56600.000000,23.583333,17108.874333,30.000000
209,210,Jasprit Bumrah,2016,2022,72,20.0,13.0,47.0,14*,6.71,...,2941.0,121.0,6/19,24.30,17,0,1.234568,2.350000,12.689370,70.285771
210,211,Yuzvendra Chahal,2016,2023,72,14.0,5.0,77.0,18*,8.55,...,3283.0,121.0,6/42,27.13,16,0,2.059374,5.500000,19.987812,64.366477
212,213,KL Rahul,2016,2023,54,52.0,8.0,1986.0,112,45.13,...,0.0,0.0,NaN,0.00,32,2,198600.000000,38.192308,59999.071231,30.000000
214,215,Hardik Pandya,2016,2023,74,55.0,7.0,1584.0,92*,33.00,...,2711.0,72.0,4/24,37.65,30,0,54.696133,28.800000,349.288840,38.976197
215,216,Jayant Yadav,2016,2022,2,2.0,1.0,3.0,2,3.00,...,61.0,1.0,1/8,61.00,1,0,3.571429,1.500000,3.021429,0.983871
216,217,Kuldeep Yadav,2017,2023,81,30.0,16.0,156.0,19,11.14,...,3683.0,134.0,6/25,27.48,12,0,3.684459,5.200000,37.281338,72.053371
217,218,Shardul Thakur,2017,2023,35,21.0,6.0,298.0,50*,19.86,...,1599.0,50.0,4/52,31.98,7,0,19.338092,14.190476,74.764475,27.709642
218,219,Shreyas Iyer,2017,2023,42,38.0,3.0,1631.0,113*,46.60,...,39.0,0.0,NaN,0.00,16,0,4408.108108,42.921053,1671.564538,30.000000
219,220,Washington Sundar,2017,2023,16,9.0,1.0,233.0,51,29.12,...,435.0,16.0,3/30,27.18,4,0,45.155039,25.888889,74.383401,9.464585
222,223,Deepak Chahar,2018,2022,13,9.0,3.0,203.0,69*,33.83,...,489.0,16.0,3/27,30.56,1,0,39.803922,22.555556,68.328732,9.950570
223,224,Rishabh Pant,2018,2022,30,26.0,1.0,865.0,125*,34.60,...,0.0,0.0,NaN,0.00,26,1,86500.000000,33.269231,26140.166923,30.000000
224,225,Mohammed Siraj,2019,2023,24,10.0,5.0,30.0,9,6.00,...,891.0,43.0,4/32,20.72,5,0,2.683363,3.000000,9.505009,26.681215
226,227,Shubman Gill,2019,2023,24,24.0,4.0,1311.0,208,65.55,...,0.0,0.0,NaN,0.00,15,0,131100.000000,54.625000,39623.882500,30.000000
228,229,Navdeep Saini,2019,2021,8,5.0,3.0,107.0,45,53.50,...,481.0,6.0,2/58,80.16,3,0,25.476190,21.400000,52.582857,3.369640
229,230,Mayank Agarwal,2020,2020,5,5.0,0.0,86.0,32,17.20,...,0.0,0.0,NaN,0.00,2,0,8600.000000,17.200000,2605.800000,30.000000
230,231,Prithvi Shaw,2020,2021,6,6.0,0.0,189.0,49,31.50,...,0.0,0.0,NaN,0.00,2,0,18900.000000,31.500000,5723.550000,30.000000
231,232,T. Natarajan,2020,2021,2,1.0,0.0,0.0,0*,0.00,...,143.0,3.0,2/70,47.66,0,0,0.000000,0.000000,0.000000,2.316523
232,233,Krunal Pandya,2021,2021,5,4.0,2.0,130.0,58*,65.00,...,223.0,2.0,1/26,111.50,1,0,57.017544,32.500000,72.355263,1.466667
233,234,Prasidh Krishna,2021,2022,14,5.0,3.0,2.0,2*,1.00,...,598.0,25.0,4/12,23.92,2,0,0.296736,0.400000,0.929021,15.103852
234,235,Ishan Kishan,2021,2023,14,13.0,1.0,510.0,210,42.50,...,0.0,0.0,NaN,0.00,5,2,51000.000000,39.230769,15422.923077,30.000000
235,236,Suryakumar Yadav,2021,2023,23,21.0,3.0,433.0,64,24.05,...,0.0,0.0,NaN,0.00,14,0,43300.000000,20.619048,13088.281905,30.000000
236,237,Rahul Chahar,2021,2021,1,1.0,0.0,13.0,13,13.00,...,54.0,3.0,3/54,18.00,0,0,21.666667,13.000000,15.600000,3.078947
237,238,Krishnappa Gowtham,2021,2021,1,1.0,0.0,2.0,2,2.00,...,49.0,1.0,1/49,49.00,1,0,4.166667,2.000000,2.650000,1.100000
238,239,Nitish Rana,2021,2021,1,1.0,0.0,7.0,7,7.00,...,10.0,0.0,NaN,0.00,0,0,38.888889,7.000000,16.566667,30.000000
239,240,Chetan Sakariya,2021,2021,1,1.0,0.0,0.0,0*,0.00,...,34.0,2.0,2/34,17.00,2,0,0.000000,0.000000,0.000000,2.666667
240,241,Sanju Samson,2021,2022,11,10.0,5.0,330.0,86*,66.00,...,0.0,0.0,NaN,0.00,7,2,33000.000000,33.000000,9995.700000,30.000000
241,242,Venkatesh Iyer,2022,2022,2,2.0,0.0,24.0,22,12.00,...,28.0,0.0,NaN,0.00,0,0,80.000000,12.000000,34.800000,30.000000
242,243,Deepak Hooda,2022,2022,10,7.0,1.0,153.0,33,25.50,...,119.0,3.0,1/6,39.66,3,0,102.000000,21.857143,73.585714,2.437826
243,244,Avesh Khan,2022,2022,5,2.0,0.0,13.0,10,6.50,...,214.0,3.0,3/66,71.33,3,0,6.103286,6.500000,7.680986,2.314766
244,245,Ruturaj Gaikwad,2022,2022,1,1.0,0.0,19.0,19,19.00,...,0.0,0.0,NaN,0.00,0,0,1900.000000,19.000000,583.300000,30.000000
245,246,Ravi Bishnoi,2022,2022,1,1.0,1.0,4.0,4*,0.00,...,69.0,1.0,1/69,69.00,0,0,8.333333,4.000000,3.700000,0.928571
246,247,Shahbaz Ahmed,2022,2022,3,1.0,0.0,0.0,0,0.00,...,125.0,3.0,2/32,41.66,1,0,0.000000,0.000000,0.000000,2.203235
247,248,Arshdeep Singh,2022,2022,3,1.0,0.0,9.0,9,9.00,...,89.0,0.0,NaN,0.00,0,0,11.392405,9.000000,9.717722,30.200000
248,249,Umran Malik,2022,2023,8,3.0,3.0,2.0,2*,0.00,...,355.0,13.0,3/57,27.30,1,0,0.606061,0.666667,0.648485,7.960071
249,250,Kuldeep Sen,2022,2022,1,1.0,1.0,2.0,2*,0.00,...,37.0,2.0,2/37,18.50,0,0,6.666667,2.000000,2.600000,2.538462

In [23]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

batting_features = [
    'Avg',
    'strike_rate',
    'Runs',
    'consistency',
    'Mat'
]

recent_df[batting_features] = scaler.fit_transform(
    recent_df[batting_features]
)

In [24]:
recent_df['batsman_score'] = (
    recent_df['Avg'] * 0.30 +
    recent_df['strike_rate'] * 0.25 +
    recent_df['Runs'] * 0.25 +
    recent_df['consistency'] * 0.10 +
    recent_df['Mat'] * 0.10
)

In [25]:
top_batsmen = recent_df.sort_values(
    by='batsman_score',
    ascending=False
)

top_batsmen[['Name', 'batsman_score']].head(11)

                Name  batsman_score
187  Shikhar Dhawan        0.718801
174     Virat Kohli        0.700387
167    Rohit Sharma        0.576949
226     Shubman Gill       0.480039
212       KL Rahul         0.406052
240     Sanju Samson       0.382616
232    Krunal Pandya       0.358957
218     Shreyas Iyer       0.338646
176  Ravindra Jadeja       0.300621
234     Ishan Kishan       0.298417
204     Kedar Jadhav       0.293557

In [26]:
recent_df['economy'] = (
    recent_df['Runs_1'] / recent_df['Balls']
) * 6

In [27]:
bowling_features = [
    'Wkt',
    'Avg_2',
    'Mdn',
    'economy',
    'Mat'
]

recent_df[bowling_features] = scaler.fit_transform(
    recent_df[bowling_features]
)

In [28]:
recent_df['bowler_score'] = (
    recent_df['Wkt'] * 0.40 +
    (1 - recent_df['Avg_2']) * 0.25 +
    recent_df['Mdn'] * 0.15 +
    (1 - recent_df['economy']) * 0.10 +
    recent_df['Mat'] * 0.10
)

In [29]:
top_bowlers = recent_df.sort_values(
    by='bowler_score',
    ascending=False
)

top_bowlers[['Name', 'bowler_score']].head(11)

                    Name  bowler_score
176      Ravindra Jadeja      0.810495
193    Bhuvneshwar Kumar      0.727542
194       Mohammed Shami      0.717069
184  Ravichandran Ashwin      0.679010
209       Jasprit Bumrah      0.633981
216        Kuldeep Yadav      0.602214
210     Yuzvendra Chahal      0.558415
214       Hardik Pandya       0.430052
201           Axar Patel      0.429770
187      Shikhar Dhawan       0.410806
224       Mohammed Siraj      0.403791

In [ ]:
top_batsmen.to_csv("top_batsmen.csv", index=False)
top_bowlers.to_csv("top_bowlers.csv", index=False)

In [30]:
wicketkeepers = recent_df[
    (recent_df['St'] > 0)
].copy()

In [31]:
wk_features = [
    'Runs',
    'Avg',
    'strike_rate',
    'Ca',
    'St',
    'Mat'
]

In [32]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

wicketkeepers[wk_features] = scaler.fit_transform(
    wicketkeepers[wk_features]
)

In [33]:
wicketkeepers['wk_score'] = (
    wicketkeepers['Runs'] * 0.25 +
    wicketkeepers['Avg'] * 0.20 +
    wicketkeepers['strike_rate'] * 0.20 +
    wicketkeepers['Ca'] * 0.15 +
    wicketkeepers['St'] * 0.10 +
    wicketkeepers['Mat'] * 0.10
)

In [34]:
top_wicketkeepers = wicketkeepers.sort_values(
    by='wk_score',
    ascending=False
)

top_wicketkeepers[['Name', 'wk_score']].head(10)

              Name  wk_score
212     KL Rahul    0.867070
240   Sanju Samson  0.311111
223  Rishabh Pant   0.306233
234   Ishan Kishan  0.206208

In [35]:
top_wicketkeepers.to_csv(
    "top_wicketkeepers.csv",
    index=False
)

In [36]:
all_rounders = recent_df.copy()

In [37]:
all_rounders = all_rounders[
    (all_rounders['Runs'] >= 500) &
    (all_rounders['Wkt'] >= 20)
].copy()

In [38]:
from sklearn.preprocessing import MinMaxScaler

features = [
    'Runs',
    'Avg',
    'strike_rate',
    'Wkt',
    'Avg_2',
    'Mdn'
]

scaler = MinMaxScaler()

all_rounders[features] = scaler.fit_transform(
    all_rounders[features]
)

ValueError: Found array with 0 sample(s) (shape=(0, 6)) while a minimum of 1 is required by MinMaxScaler.

In [39]:
print(recent_df[['Name', 'Runs', 'Wkt']].head(20))

                    Name      Runs       Wkt
167        Rohit Sharma   0.761746  0.041885
174         Virat Kohli   1.000000  0.020942
176      Ravindra Jadeja  0.195844  1.000000
184  Ravichandran Ashwin  0.054815  0.790576
187      Shikhar Dhawan   0.526671  0.000000
193    Bhuvneshwar Kumar  0.042797  0.738220
194       Mohammed Shami  0.015816  0.848168
201           Axar Patel  0.031943  0.303665
204         Kedar Jadhav  0.107691  0.141361
205        Manish Pandey  0.043883  0.000000
209       Jasprit Bumrah  0.003644  0.633508
210     Yuzvendra Chahal  0.005970  0.633508
212           KL Rahul    0.153977  0.000000
214       Hardik Pandya   0.122810  0.376963
215         Jayant Yadav  0.000233  0.005236
216        Kuldeep Yadav  0.012095  0.701571
217       Shardul Thakur  0.023104  0.261780
218         Shreyas Iyer  0.126454  0.000000
219    Washington Sundar  0.018065  0.083770
222        Deepak Chahar  0.015739  0.083770

In [40]:
all_rounders = recent_df[
    (recent_df['Runs'] >= 300) &
    (recent_df['Wkt'] >= 10)
].copy()

In [41]:
all_rounders

Empty DataFrame
Columns: [No, Name, First, Last, Mat, Inn, NO.1, Runs, HS, Avg, Balls, Mdn, Runs_1, Wkt, BBM, Avg_2, Ca, St, strike_rate, consistency, batsman_score, bowler_score, economy]
Index: []

[0 rows x 23 columns]

In [42]:
recent_df[['Name', 'Runs', 'Wkt']].sort_values(
    by=['Runs', 'Wkt'],
    ascending=False
).head(30)

                    Name      Runs       Wkt
174         Virat Kohli   1.000000  0.020942
167        Rohit Sharma   0.761746  0.041885
187      Shikhar Dhawan   0.526671  0.000000
176      Ravindra Jadeja  0.195844  1.000000
212           KL Rahul    0.153977  0.000000
218         Shreyas Iyer  0.126454  0.000000
214       Hardik Pandya   0.122810  0.376963
204         Kedar Jadhav  0.107691  0.141361
226         Shubman Gill  0.101644  0.000000
223        Rishabh Pant   0.067065  0.000000
184  Ravichandran Ashwin  0.054815  0.790576
205        Manish Pandey  0.043883  0.000000
193    Bhuvneshwar Kumar  0.042797  0.738220
234         Ishan Kishan  0.039541  0.000000
235     Suryakumar Yadav  0.033571  0.000000
201           Axar Patel  0.031943  0.303665
240         Sanju Samson  0.025585  0.000000
217       Shardul Thakur  0.023104  0.261780
219    Washington Sundar  0.018065  0.083770
194       Mohammed Shami  0.015816  0.848168
222        Deepak Chahar  0.015739  0.083770
230         Prithvi Shaw  0.014653  0.000000
216        Kuldeep Yadav  0.012095  0.701571
242         Deepak Hooda  0.011862  0.015707
232        Krunal Pandya  0.010079  0.010471
228        Navdeep Saini  0.008296  0.031414
229       Mayank Agarwal  0.006668  0.000000
210     Yuzvendra Chahal  0.005970  0.633508
209       Jasprit Bumrah  0.003644  0.633508
224       Mohammed Siraj  0.002326  0.225131

In [43]:
from sklearn.preprocessing import MinMaxScaler

features = [
    'Runs',
    'Avg',
    'strike_rate',
    'Wkt',
    'Avg_2',
    'Mdn'
]

scaler = MinMaxScaler()

all_rounders[features] = scaler.fit_transform(
    all_rounders[features]
)

ValueError: Found array with 0 sample(s) (shape=(0, 6)) while a minimum of 1 is required by MinMaxScaler.

In [44]:
all_rounders = recent_df[
    (recent_df['Runs'] > 100) &
    (recent_df['Wkt'] > 5)
].copy()

In [45]:
print(all_rounders.shape)
print(all_rounders[['Name', 'Runs', 'Wkt']].head())

(0, 23)
Empty DataFrame
Columns: [Name, Runs, Wkt]
Index: []

In [46]:
import pandas as pd
import numpy as np

df_again = pd.read_csv("data/Indian ODI Cricketers.csv")

In [47]:
df_again.replace('—', np.nan, inplace=True)

numeric_cols = [
    'Inn',
    'NO.1',
    'Runs',
    'Avg',
    'Balls',
    'Mdn',
    'Runs_1',
    'Wkt',
    'Avg_2'
]

for col in numeric_cols:
    df_again[col] = pd.to_numeric(df_again[col], errors='coerce')

df_again[numeric_cols] = df_again[numeric_cols].fillna(0)

In [48]:
recent_df_2 = df_again[df_again['Last'] >= 2020].copy()

In [49]:
recent_df_2['Balls'] = recent_df_2['Balls'].replace(0, 1)

recent_df_2['strike_rate'] = (
    recent_df_2['Runs'] / recent_df_2['Balls']
) * 100

In [50]:
all_rounders = recent_df_2[
    (recent_df_2['Runs'] >= 500) &
    (recent_df_2['Wkt'] >= 20)
].copy()

In [51]:
print(all_rounders[['Name', 'Runs', 'Wkt']])

                    Name    Runs    Wkt
176      Ravindra Jadeja  2526.0  191.0
184  Ravichandran Ashwin   707.0  151.0
193    Bhuvneshwar Kumar   552.0  141.0
204         Kedar Jadhav  1389.0   27.0
214       Hardik Pandya   1584.0   72.0

In [52]:
all_rounders = recent_df_2[
    (recent_df_2['Runs'] >= 300) &
    (recent_df_2['Wkt'] >= 10)
].copy()

In [53]:
print(all_rounders[['Name', 'Runs', 'Wkt']])

                    Name    Runs    Wkt
176      Ravindra Jadeja  2526.0  191.0
184  Ravichandran Ashwin   707.0  151.0
193    Bhuvneshwar Kumar   552.0  141.0
201           Axar Patel   412.0   58.0
204         Kedar Jadhav  1389.0   27.0
214       Hardik Pandya   1584.0   72.0

In [54]:
from sklearn.preprocessing import MinMaxScaler

features = [
    'Runs',
    'Avg',
    'strike_rate',
    'Wkt',
    'Avg_2',
    'Mdn'
]

scaler = MinMaxScaler()

all_rounders[features] = scaler.fit_transform(
    all_rounders[features]
)

In [55]:
all_rounders['allrounder_score'] = (
    all_rounders['Runs'] * 0.25 +
    all_rounders['Avg'] * 0.15 +
    all_rounders['strike_rate'] * 0.15 +
    all_rounders['Wkt'] * 0.25 +
    (1 - all_rounders['Avg_2']) * 0.10 +
    all_rounders['Mdn'] * 0.10
)

In [56]:
top_all_rounders = all_rounders.sort_values(
    by='allrounder_score',
    ascending=False
)

top_all_rounders[['Name', 'allrounder_score']].head(10)

                    Name  allrounder_score
176      Ravindra Jadeja          0.706439
204         Kedar Jadhav          0.415539
214       Hardik Pandya           0.388310
184  Ravichandran Ashwin          0.356642
193    Bhuvneshwar Kumar          0.332161
201           Axar Patel          0.212566

In [57]:
final_xi = pd.concat([
    top_batsmen.head(4),
    top_wicketkeepers.head(1),
    top_all_rounders.head(2),
    top_bowlers.head(4)
])

final_xi[['Name']]

                    Name
187      Shikhar Dhawan
174         Virat Kohli
167        Rohit Sharma
226         Shubman Gill
212           KL Rahul
176      Ravindra Jadeja
204         Kedar Jadhav
176      Ravindra Jadeja
193    Bhuvneshwar Kumar
194       Mohammed Shami
184  Ravichandran Ashwin

In [58]:
final_xi = final_xi.drop_duplicates(subset='Name')

In [59]:
final_xi

,No,Name,First,Last,Mat,Inn,NO.1,Runs,HS,Avg,...,Avg_2,Ca,St,strike_rate,consistency,batsman_score,bowler_score,economy,wk_score,allrounder_score
187,188,Shikhar Dhawan,2010,2022,0.608059,164.0,10.0,0.526671,143,0.668333,...,0.000000,83.0,0.0,1.000000,0.758274,0.718801,30.000000,NaN,NaN,NaN
174,175,Virat Kohli,2008,2023,1.000000,265.0,40.0,1.000000,183,0.868485,...,166.250000,141.0,0.0,0.002962,0.891015,0.700387,2.379372,NaN,NaN,NaN
167,168,Rohit Sharma,2007,2023,0.886447,236.0,34.0,0.761746,264,0.736818,...,64.370000,87.0,0.0,0.002439,0.762130,0.576949,4.858926,NaN,NaN,NaN
226,227,Shubman Gill,2019,2023,0.084249,24.0,4.0,0.101644,208,0.993182,...,0.000000,15.0,0.0,0.192993,1.000000,0.480039,30.000000,NaN,NaN,NaN
212,213,KL Rahul,2016,2023,1.000000,52.0,8.0,1.000000,112,0.335350,...,0.000000,1.0,1.0,1.000000,0.699173,0.406052,0.369414,0.000000,0.86707,NaN
176,177,Ravindra Jadeja,2009,2023,174.000000,118.0,41.0,1.000000,87,0.667502,...,0.940252,65.0,0.0,0.181364,NaN,NaN,NaN,NaN,NaN,0.706439
204,205,Kedar Jadhav,2014,2020,73.000000,52.0,19.0,0.462157,120,1.000000,...,1.000000,33.0,0.0,1.000000,NaN,NaN,NaN,NaN,NaN,0.415539
193,194,Bhuvneshwar Kumar,2012,2022,0.439560,55.0,16.0,0.042797,53*,0.214394,...,0.211188,29.0,0.0,0.000014,0.183732,0.137350,0.727542,0.589050,NaN,NaN
194,195,Mohammed Shami,2013,2023,0.326007,43.0,19.0,0.015816,25,0.128788,...,0.156271,29.0,0.0,0.000007,0.086850,0.083878,0.717069,0.649955,NaN,NaN
184,185,Ravichandran Ashwin,2010,2022,0.410256,63.0,20.0,0.054815,65,0.243485,...,0.201444,30.0,0.0,0.000017,0.205441,0.148323,0.679010,0.572970,NaN,NaN

In [60]:
final_xi[['Name']]

                    Name
187      Shikhar Dhawan
174         Virat Kohli
167        Rohit Sharma
226         Shubman Gill
212           KL Rahul
176      Ravindra Jadeja
204         Kedar Jadhav
193    Bhuvneshwar Kumar
194       Mohammed Shami
184  Ravichandran Ashwin

In [61]:
final_squad = pd.concat([
    top_batsmen.head(5),
    top_wicketkeepers.head(2),
    top_all_rounders.head(3),
    top_bowlers.head(5)
])

final_squad = final_squad.drop_duplicates(subset='Name')

final_squad[['Name']]

                    Name
187      Shikhar Dhawan
174         Virat Kohli
167        Rohit Sharma
226         Shubman Gill
212           KL Rahul
240         Sanju Samson
176      Ravindra Jadeja
204         Kedar Jadhav
214       Hardik Pandya
193    Bhuvneshwar Kumar
194       Mohammed Shami
184  Ravichandran Ashwin
209       Jasprit Bumrah

In [62]:
final_squad = pd.concat([
    top_batsmen.head(5),
    top_wicketkeepers.head(2),
    top_all_rounders.head(3),
    top_bowlers.head(5)
])

final_squad = final_squad.drop_duplicates(subset='Name')

In [63]:
print(len(final_squad))

13

In [64]:
needed = 15 - len(final_squad)

In [65]:
remaining_players = pd.concat([
    top_batsmen,
    top_bowlers,
    top_all_rounders,
    top_wicketkeepers
])

remaining_players = remaining_players.drop_duplicates(subset='Name')

remaining_players = remaining_players[
    ~remaining_players['Name'].isin(final_squad['Name'])
]

extras = remaining_players.head(needed)

final_squad = pd.concat([final_squad, extras])

final_squad = final_squad.drop_duplicates(subset='Name')

In [66]:
print(len(final_squad))

15

In [67]:
final_squad

,No,Name,First,Last,Mat,Inn,NO.1,Runs,HS,Avg,...,Avg_2,Ca,St,strike_rate,consistency,batsman_score,bowler_score,economy,wk_score,allrounder_score
187,188,Shikhar Dhawan,2010,2022,0.608059,164.0,10.0,0.526671,143,0.668333,...,0.000000,83.000000,0.0,1.000000,0.758274,0.718801,30.000000,NaN,NaN,NaN
174,175,Virat Kohli,2008,2023,1.000000,265.0,40.0,1.000000,183,0.868485,...,166.250000,141.000000,0.0,0.002962,0.891015,0.700387,2.379372,NaN,NaN,NaN
167,168,Rohit Sharma,2007,2023,0.886447,236.0,34.0,0.761746,264,0.736818,...,64.370000,87.000000,0.0,0.002439,0.762130,0.576949,4.858926,NaN,NaN,NaN
226,227,Shubman Gill,2019,2023,0.084249,24.0,4.0,0.101644,208,0.993182,...,0.000000,15.000000,0.0,0.192993,1.000000,0.480039,30.000000,NaN,NaN,NaN
212,213,KL Rahul,2016,2023,0.194139,52.0,8.0,0.153977,112,0.683788,...,0.000000,32.000000,2.0,0.292360,0.699173,0.406052,30.000000,NaN,NaN,NaN
240,241,Sanju Samson,2021,2022,0.000000,10.0,5.0,0.000000,86*,1.000000,...,0.000000,0.074074,1.0,0.000000,0.604119,0.382616,0.353663,0.000000,0.311111,NaN
176,177,Ravindra Jadeja,2009,2023,174.000000,118.0,41.0,1.000000,87,0.667502,...,0.940252,65.000000,0.0,0.181364,NaN,NaN,NaN,NaN,NaN,0.706439
204,205,Kedar Jadhav,2014,2020,73.000000,52.0,19.0,0.462157,120,1.000000,...,1.000000,33.000000,0.0,1.000000,NaN,NaN,NaN,NaN,NaN,0.415539
214,215,Hardik Pandya,2016,2023,74.000000,55.0,7.0,0.554399,92*,0.674660,...,0.981132,30.000000,0.0,0.420679,NaN,NaN,NaN,NaN,NaN,0.388310
193,194,Bhuvneshwar Kumar,2012,2022,0.439560,55.0,16.0,0.042797,53*,0.214394,...,0.211188,29.000000,0.0,0.000014,0.183732,0.137350,0.727542,0.589050,NaN,NaN
194,195,Mohammed Shami,2013,2023,0.326007,43.0,19.0,0.015816,25,0.128788,...,0.156271,29.000000,0.0,0.000007,0.086850,0.083878,0.717069,0.649955,NaN,NaN
184,185,Ravichandran Ashwin,2010,2022,0.410256,63.0,20.0,0.054815,65,0.243485,...,0.201444,30.000000,0.0,0.000017,0.205441,0.148323,0.679010,0.572970,NaN,NaN
209,210,Jasprit Bumrah,2016,2022,0.260073,20.0,13.0,0.003644,14*,0.101667,...,0.146165,17.000000,0.0,0.000002,0.043021,0.061721,0.633981,0.537408,NaN,NaN
232,233,Krunal Pandya,2021,2021,0.014652,4.0,2.0,0.010079,58*,0.984848,...,111.500000,1.000000,0.0,0.000084,0.594966,0.358957,1.466667,NaN,NaN,NaN
218,219,Shreyas Iyer,2017,2023,0.150183,38.0,3.0,0.126454,113*,0.706061,...,0.000000,16.000000,0.0,0.006489,0.785740,0.338646,30.000000,NaN,NaN,NaN